spring.application.name=lirio-Seda

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.port=8470

security.jwt.secret=${JWT_SECRET:MiClaveSuperSecretaParaJWT2026MiClaveSuperSecreta}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:https://liroseda.noudat.com}
